Add JSONB filter
eliberty/api-bundle pull request #54
Opened 2019-06-24 07:57 UTC by aleliberty

2019-06-26 13:54 UTC, freliberty requested changes

2019-06-26 13:54 UTC, freliberty commented on Eliberty/ApiBundle/Doctrine/Orm/Filter/JsonbFilter.php
> +                    if ($value === 'UNSET') {
Empty plutot que Unset

2019-06-26 13:54 UTC, freliberty commented on Eliberty/ApiBundle/Doctrine/Orm/Filter/JsonbFilter.php
> +            foreach ($values as $key => $value) {
Refacto découpe en private function + test unitaire + commentaire

2019-06-28 07:33 UTC, tleliberty requested changes

2019-06-28 07:33 UTC, tleliberty commented on Eliberty/ApiBundle/Resources/config/filter.yml
> +    eliberty.api.doctrine.orm.jsonb_filter:
Utiliser la nouvelle notation Symfony4 : enlever cet alias et mettre directement la classe.

2019-06-28 07:33 UTC, tleliberty commented on Eliberty/ApiBundle/Doctrine/Orm/Filter/JsonbFilter.php
> +            if (!isset($jsonbFieldNames[$property]) /* || !$this->isPropertyEnabled($property)  */) {
supprimer commentaires

2019-06-28 07:33 UTC, tleliberty commented on Eliberty/ApiBundle/Doctrine/Orm/Filter/JsonbFilter.php
> +                $conditions = $queryBuilder->expr()->orX();
inutile ?

2019-06-28 07:33 UTC, tleliberty commented on Eliberty/ApiBundle/Doctrine/Orm/Filter/JsonbFilter.php
> +                if ($conditions->count() > 0) {
inutile ?

2019-07-01 15:32 UTC, aleliberty commented on Eliberty/ApiBundle/Doctrine/Orm/Filter/JsonbFilter.php
> +                    if ($value === 'UNSET') {
OK

2019-07-03 07:08 UTC, aleliberty commented on Eliberty/ApiBundle/Resources/config/filter.yml
> +    eliberty.api.doctrine.orm.jsonb_filter:
OK

2019-07-03 07:09 UTC, aleliberty commented on Eliberty/ApiBundle/Doctrine/Orm/Filter/JsonbFilter.php
> +                if ($conditions->count() > 0) {
supprimé

2019-07-03 07:09 UTC, aleliberty commented on Eliberty/ApiBundle/Doctrine/Orm/Filter/JsonbFilter.php
> +            if (!isset($jsonbFieldNames[$property]) /* || !$this->isPropertyEnabled($property)  */) {
OK

2019-07-03 07:09 UTC, aleliberty commented on Eliberty/ApiBundle/Doctrine/Orm/Filter/JsonbFilter.php
> +            foreach ($values as $key => $value) {
OK

2019-07-03 07:24 UTC, freliberty approved these changes

2019-07-03 07:40 UTC, tleliberty approved these changes
J'approuve bien que le service n'ait pas été mis à jour en sF4, ça demandait trop de job sur cette PR déjà trop grosse ;)

2019-07-03 07:56 UTC, merged