Add new filter for notification API
eliberty/api-bundle pull request #66
Opened 2020-02-19 14:54 UTC by aleliberty

2020-02-20 07:44 UTC, gveliberty requested changes

2020-02-20 07:44 UTC, gveliberty commented on Eliberty/ApiBundle/Doctrine/Orm/Filter/CoalescentOrderFilter.php
> +    private $coalepseOrderParameter = 'corder';
typo dans le nom de la variable $coale**ps**eOrderParameter (à corriger ailleurs dans le code du coup)

2020-02-20 07:44 UTC, gveliberty commented on Eliberty/ApiBundle/Doctrine/Orm/Filter/CoalescentOrderFilter.php
> +                $description[sprintf('%s[]', $this->coalepseOrderParameter)] = [
typo dans le nom de la variable $coale**ps**eOrderParameter

2020-02-20 07:44 UTC, gveliberty commented on Eliberty/ApiBundle/Doctrine/Orm/Filter/CoalescentOrderFilter.php
> +        return $request->query->get($this->coalepseOrderParameter, []);
typo dans le nom de la variable $coale**ps**eOrderParameter

2020-02-24 08:27 UTC, rseliberty approved these changes

2020-02-24 08:55 UTC, gveliberty approved these changes

2020-02-24 08:57 UTC, merged